/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d2c840bb-d377-4a79-8247-539b16495319",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_0hJRnusLP",
    "aws_user_pools_web_client_id": "3taitrvsh6rfc9ocqmu5tua5em",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://zqwu777ewrffxbf6kfyj6xthb4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zn3q5ekuubfa7pmsad6qh3e2yu",
    "aws_user_files_s3_bucket": "amplify-bucket233435-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
