/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d2c840bb-d377-4a79-8247-539b16495319",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_0hJRnusLP",
    "aws_user_pools_web_client_id": "3taitrvsh6rfc9ocqmu5tua5em",
    "oauth": {}
};


export default awsmobile;
